# 📚 AI Research Paper Intelligence System

## Notebook 1: Data Preparation

### Objectives
- Load the ML-ArXiv research paper dataset
- Explore the dataset
- Clean the dataset
- Save the cleaned dataset for later notebooks

In [1]:
import os
import sys
import importlib

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

import utils.preprocessing
importlib.reload(utils.preprocessing)

from utils.preprocessing import preprocess, text_statistics

In [2]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
from datasets import load_dataset

dataset = load_dataset("CShorten/ML-ArXiv-Papers")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
        num_rows: 117592
    })
})

In [5]:
# Convert Hugging Face dataset to Pandas DataFrame
papers = dataset["train"].to_pandas()

print("Dataset converted successfully!")

Dataset converted successfully!

In [6]:
papers.head()

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint...
1,1,1.0,Sensor Networks with Random Links: Topology Design for Distributed\n Consensus,"In a sensor network, in practice, the communication among sensors is subject\nto:(1) errors or failures at random times; (3) costs; and(2) constraints since\nsensors and networks operate under s..."
2,2,2.0,The on-line shortest path problem under partial monitoring,The on-line shortest path problem is considered under various models of\npartial monitoring. Given a weighted directed acyclic graph whose edge weights\ncan change in an arbitrary (adversarial) ...
3,3,3.0,A neural network approach to ordinal regression,"Ordinal regression is an important type of learning, which has properties of\nboth classification and regression. Here we describe a simple and effective\napproach to adapt a traditional neural ..."
4,4,4.0,Parametric Learning and Monte Carlo Optimization,"This paper uncovers and explores the close relationship between Monte Carlo\nOptimization of a parametrized integral (MCO), Parametric machine-Learning\n(PL), and `blackbox' or `oracle'-based op..."

In [7]:
print(f"Number of Rows    : {papers.shape[0]}")
print(f"Number of Columns : {papers.shape[1]}")

Number of Rows    : 117592
Number of Columns : 4

In [8]:
papers.info()

<class 'pandas.DataFrame'>
RangeIndex: 117592 entries, 0 to 117591
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0.1  117592 non-null  int64
 1   Unnamed: 0    112592 non-null  float64
 2   title         117592 non-null  str
 3   abstract      117592 non-null  str
dtypes: float64(1), int64(1), str(2)
memory usage: 141.6 MB

In [9]:
papers.isnull().sum()

Unnamed: 0.1       0
Unnamed: 0      5000
title              0
abstract           0
dtype: int64

In [10]:
papers = papers.drop(columns=["Unnamed: 0.1", "Unnamed: 0"])

papers.head()

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint...
1,Sensor Networks with Random Links: Topology Design for Distributed\n Consensus,"In a sensor network, in practice, the communication among sensors is subject\nto:(1) errors or failures at random times; (3) costs; and(2) constraints since\nsensors and networks operate under s..."
2,The on-line shortest path problem under partial monitoring,The on-line shortest path problem is considered under various models of\npartial monitoring. Given a weighted directed acyclic graph whose edge weights\ncan change in an arbitrary (adversarial) ...
3,A neural network approach to ordinal regression,"Ordinal regression is an important type of learning, which has properties of\nboth classification and regression. Here we describe a simple and effective\napproach to adapt a traditional neural ..."
4,Parametric Learning and Monte Carlo Optimization,"This paper uncovers and explores the close relationship between Monte Carlo\nOptimization of a parametrized integral (MCO), Parametric machine-Learning\n(PL), and `blackbox' or `oracle'-based op..."

In [11]:
papers = papers.dropna()

print("Remaining papers:", len(papers))

Remaining papers: 117592

In [12]:
papers = papers.drop_duplicates()

print("Unique papers:", len(papers))

Unique papers: 117569

In [13]:
papers.sample(5)

,title,abstract
40623,A Quotient Space Formulation for Generative Statistical Analysis of\n Graphical Data,"Complex analyses involving multiple, dependent random quantities often lead\nto graphical models - a set of nodes denoting variables of interest, and\ncorresponding edges denoting statistical in..."
15313,Stochastic Nonconvex Optimization with Large Minibatches,"We study stochastic optimization of nonconvex loss functions, which are\ntypical objectives for training neural networks. We propose stochastic\napproximation algorithms which optimize a series ..."
112636,Symbolic-Regression Boosting,"Modifying standard gradient boosting by replacing the embedded weak learner\nin favor of a strong(er) one, we present SyRBo: Symbolic-Regression Boosting.\nExperiments over 98 regression datasets ..."
63055,One Weight Bitwidth to Rule Them All,Weight quantization for deep ConvNets has shown promising results for\napplications such as image classification and semantic segmentation and is\nespecially important for applications where mem...
83008,Gradient Assisted Learning,"In decentralized settings, collaborations between different organizations,\nsuch as financial institutions, medical centers, and retail markets, are\ncrucial to providing improved service and pe..."

In [14]:
papers.to_csv("../data/cleaned_papers.csv", index=False)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!

In [15]:
import os

print(os.listdir(".."))

['data', 'dataset.md', 'models', 'notebooks', 'requirement.txt', 'uploads', 'utils', 'vector_db', 'venv']