# 🔍 AI Research Paper Intelligence System

## Notebook 3: Semantic Search

### Objectives
- Load cleaned dataset
- Generate embeddings
- Create FAISS index
- Perform semantic search

In [1]:
import os
import sys
import importlib

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

import utils.preprocessing
importlib.reload(utils.preprocessing)

from utils.preprocessing import preprocess, text_statistics

In [2]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
import faiss

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
papers = pd.read_csv("../data/cleaned_papers.csv")

print("Dataset Loaded Successfully!")
papers.head()

Dataset Loaded Successfully!

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [4]:
papers = papers[["title", "abstract"]]

papers.head()

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [5]:
papers = papers.sample(5000, random_state=42).reset_index(drop=True)

print("Number of Papers:", len(papers))

Number of Papers: 5000

In [6]:
model = SentenceTransformer("all-MiniLM-L6-v2")

print("Model Loaded Successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Model Loaded Successfully!

In [7]:
embeddings = model.encode(
    papers["abstract"].tolist(),
    show_progress_bar=True
)

print("Embeddings Shape:", embeddings.shape)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Embeddings Shape: (5000, 384)

In [8]:
embeddings = np.array(embeddings).astype("float32")

In [9]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

print("FAISS Index Created!")
print("Total Vectors:", index.ntotal)

FAISS Index Created!
Total Vectors: 5000

In [10]:
faiss.write_index(index, "../vector_db/research_index.faiss")

print("FAISS Index Saved!")

FAISS Index Saved!

In [11]:
def search_papers(query, top_k=5):
    # Convert query to embedding
    query_embedding = model.encode([query])

    query_embedding = np.array(query_embedding).astype("float32")

    distances, indices = index.search(query_embedding, top_k)

    results = papers.iloc[indices[0]][["title", "abstract"]]

    return results

In [12]:
results = search_papers("Transformer models for NLP")

results

,title,abstract
2364,WaLDORf: Wasteless Language-model Distillation...,Transformer based Very Large Language Models...
4089,Conditioned Natural Language Generation using ...,Transformer-based language models have shown...
4436,Learning to Merge Tokens in Vision Transformers,Transformers are widely applied to solve nat...
3211,DeFINE: DEep Factorized INput Token Embeddings...,"For sequence models with large vocabularies,..."
4405,Transformer Acceleration with Dynamic Sparse A...,Transformers are the mainstream of NLP appli...

In [13]:
results = search_papers("Deep Learning for Image Classification")

results

,title,abstract
2867,SWP-Leaf NET: a novel multistage approach for ...,Modern scientific and technological advances...
41,A PCA-Based Convolutional Network,"In this paper, we propose a novel unsupervis..."
1219,Classification of Skin Cancer Images using Con...,Skin cancer is the most common human maligna...
3101,Deep convolutional Gaussian processes,We propose deep convolutional Gaussian proce...
1129,Improving Deep Neural Networks with Probabilis...,We present a probabilistic variant of the re...

In [14]:
results = search_papers("Computer Vision")

results

,title,abstract
3671,TasselNet: Counting maize tassels in the wild ...,Accurately counting maize tassels is importa...
1187,Heatmap-based Object Detection and Tracking wi...,The main topic of this paper is a brief over...
4733,Optic disc and fovea localisation in ultra-wid...,We propose a convolutional neural network fo...
322,Segmentation of blood vessels in retinal fundu...,"In recent years, several automatic segmentat..."
173,Real-world Mapping of Gaze Fixations Using Ins...,Research studies have shown that a large pro...

In [15]:
results = search_papers("Large Language Models")

results

,title,abstract
2931,On the importance of pre-training data volume ...,Recent advances in language modeling have le...
756,Structure-Level Knowledge Distillation For Mul...,Multilingual sequence labeling is a task of ...
138,Scaling Laws Under the Microscope: Predicting ...,Neural scaling laws define a predictable rel...
471,Increasing Robustness to Spurious Correlations...,Neural NLP models tend to rely on spurious c...
1293,Should we Stop Training More Monolingual Model...,Most work in NLP makes the assumption that i...

In [16]:
# Save the Sentence Transformer model locally

model.save("../models/all-MiniLM-L6-v2")

print("✅ Model saved successfully!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Model saved successfully!

In [17]:
model = SentenceTransformer("../models/all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [18]:
import os
import sys
import importlib

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

import utils.semantic_search
importlib.reload(utils.semantic_search)

from utils.semantic_search import SemanticSearch

In [19]:
import pandas as pd

papers = pd.read_csv("../data/cleaned_papers.csv")

papers = papers[["title", "abstract"]]

papers = papers.sample(
    5000,
    random_state=42
).reset_index(drop=True)

papers.head()

,title,abstract
0,Semantic Parsing to Manipulate Relational Data...,Chatbots and AI assistants have claimed thei...
1,Zero-shot Relation Classification from Side In...,We propose a zero-shot learning relation cla...
2,Assembling Semantically-Disentangled Represent...,Deep neural networks can form high-level hie...
3,Exploring Neural Networks Quantization via Lay...,Quantization is an essential step in the eff...
4,Pitch-Informed Instrument Assignment Using a D...,This paper proposes a deep convolutional neu...

In [20]:
search_engine = SemanticSearch()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [21]:
embeddings = search_engine.create_embeddings(
    papers
)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

In [22]:
search_engine.build_index(
    embeddings
)

✅ Indexed 5000 papers.

In [23]:
search_engine.save_index(
    "../vector_db/research_index.faiss"
)

✅ Index saved.

In [24]:
results = search_engine.search(
    "Transformer models for NLP"
)

results

,title,abstract
2364,WaLDORf: Wasteless Language-model Distillation...,Transformer based Very Large Language Models...
4089,Conditioned Natural Language Generation using ...,Transformer-based language models have shown...
4436,Learning to Merge Tokens in Vision Transformers,Transformers are widely applied to solve nat...
3211,DeFINE: DEep Factorized INput Token Embeddings...,"For sequence models with large vocabularies,..."
4405,Transformer Acceleration with Dynamic Sparse A...,Transformers are the mainstream of NLP appli...

In [25]:
import os
import sys
import importlib

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

import utils.semantic_search
importlib.reload(utils.semantic_search)

from utils.semantic_search import SemanticSearch

print("✅ Semantic Search module imported successfully!")

✅ Semantic Search module imported successfully!

In [26]:
import pandas as pd

papers = pd.read_csv("../data/cleaned_papers.csv")

papers = papers[["title", "abstract"]]

papers = papers.sample(
    5000,
    random_state=42
).reset_index(drop=True)

print("Total Papers:", len(papers))

papers.head()

Total Papers: 5000

,title,abstract
0,Semantic Parsing to Manipulate Relational Data...,Chatbots and AI assistants have claimed thei...
1,Zero-shot Relation Classification from Side In...,We propose a zero-shot learning relation cla...
2,Assembling Semantically-Disentangled Represent...,Deep neural networks can form high-level hie...
3,Exploring Neural Networks Quantization via Lay...,Quantization is an essential step in the eff...
4,Pitch-Informed Instrument Assignment Using a D...,This paper proposes a deep convolutional neu...

In [27]:
search_engine = SemanticSearch()

print("✅ Model Loaded Successfully!")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

✅ Model Loaded Successfully!

In [28]:
embeddings = search_engine.create_embeddings(papers)

print(embeddings.shape)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

(5000, 384)

In [29]:
search_engine.build_index(embeddings)

✅ Indexed 5000 papers.

In [30]:
search_engine.save_index("../vector_db/research_index.faiss")

✅ Index saved.

In [31]:
results = search_engine.search(
    "Transformer models for NLP",
    top_k=5
)

results

,title,abstract
2364,WaLDORf: Wasteless Language-model Distillation...,Transformer based Very Large Language Models...
4089,Conditioned Natural Language Generation using ...,Transformer-based language models have shown...
4436,Learning to Merge Tokens in Vision Transformers,Transformers are widely applied to solve nat...
3211,DeFINE: DEep Factorized INput Token Embeddings...,"For sequence models with large vocabularies,..."
4405,Transformer Acceleration with Dynamic Sparse A...,Transformers are the mainstream of NLP appli...